backend:
    name: github
    repo: VincentPFG/neo

media_folder: static/uploads
public_folder: /uploads

collections:
    -
        name: posts
        label: Posts
        folder: blog
        create: true
        fields: 
            -
                label: Titre
                name: title
                widget: string
            -
                label: Publish Date
                name: date
                widget: date
            -
                label: Body
                name: body
                widget: markdown