backend:
    name: github
    repo: VincentPFG/

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
-   
    name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
    -
        label: "Titre"
        name: "title"
        widget: "string"
    -
        label: "Excerpt"
        name: "excerpt"
        widget: "string"
    -
        label: "Publish Date"
        name: "date"
        widget: "date"
    -
        label: "Body"
        name: "body"
        widget: "markdown"
    -
        label: 'coucou'
        name: 'test'
        widget: 'string'
